<#
.SYNOPSIS  Gate: build the site and publish ONLY the static output to the PUBLIC deploy repo.
.DESCRIPTION
  Internal dev repo (git-repo) holds source + docs. This script builds the Astro site and pushes
  the contents of dist/ into the PUBLIC repo (public-repo), which Azure Static Web Apps deploys from.
  Run this only after changes are reviewed/approved. Property: IT Ant ehf (itant.is).
  NOTE: remotes are LOCAL placeholders during bootstrap; swap to the private GitHub remotes later.
#>
[CmdletBinding()]
param([switch]$Push)

$ErrorActionPreference = 'Stop'
$work   = Split-Path -Parent $PSScriptRoot          # webmaster\
$root   = Split-Path -Parent $work                  # <prop>-web\
$public = Join-Path $root 'public-repo'
$stage  = Join-Path $root '.publish-stage'

Write-Host '==> Building static site (npm run build)...' -ForegroundColor Cyan
Push-Location $work
if (Test-Path (Join-Path $work 'package-lock.json')) { npm ci } else { npm install }
npm run build
Pop-Location
$dist = Join-Path $work 'dist'
if (-not (Test-Path $dist)) { throw "Build produced no dist/ at $dist" }

Write-Host '==> Staging public deploy clone...' -ForegroundColor Cyan
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
git clone -q $public $stage
# wipe tracked working files (keep .git) so deletions propagate
Get-ChildItem -Force $stage | Where-Object { $_.Name -ne '.git' } | Remove-Item -Recurse -Force
Copy-Item (Join-Path $dist '*') $stage -Recurse -Force
Copy-Item (Join-Path $work 'staticwebapp.config.json') $stage -Force
@'
# IT Ant ehf — PUBLIC deploy artifact
Built static output only. Do not edit by hand. Generated by scripts/publish.ps1 in the internal repo.
Deployed to Azure Static Web Apps for itant.is.
'@ | Set-Content (Join-Path $stage 'README.md') -Encoding UTF8

git -C $stage add -A
git -C $stage -c user.email='webmaster@g9.is' -c user.name='G9 Webmaster (Copilot)' commit -q -m "publish: IT Ant ehf static build" 2>&1 | Out-Null
if ($Push) { git -C $stage push -q origin HEAD:main; Write-Host '==> Pushed to public-repo.' -ForegroundColor Green }
else { Write-Host '==> Dry run complete (staged, not pushed). Re-run with -Push to publish.' -ForegroundColor Yellow }
Write-Host "Staged at: $stage"
